.TH NOTETAK 1
.SH NAME
notetak \- note taking application for GNOME
.SH SYNOPSIS
.B notetak
.IR "" [ directory ]
.DESCRIPTION
.B notetak
is a simple note taking application for GNOME,
inspired by the Notational Velocity for OS X.
The program manages a list of textual notes, each with a title.
You write the title and press enter to create a new note.
The title field simultaneously works as a search field: instead of pressing
enter to create a new field, you may also select one of the existing 
notes from the pop-down list.
.PP
All changes are saved automatically, the File/Save function is
unnecessary.
.PP
Stuff are saved in a directory, called 
.I ~/.notetak
by default.
Each note is in a separate file in the directory.
You can specify another name on the command line if you want.
